stages:  
  - init       # List of stages for jobs, and their order of execution
  - build
  - test

cache:
  paths:
      - node_modules/

init-job:       # This job installs the npm packages required
  stage: init
  only:         # Runs only during merge requests
    - merge_requests
  script:
    - echo "Installing the npm packages..."
    - npm i rimraf
    - npm ci


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:          # Runs only during merge requests
    - merge_requests
  script:
    - echo "Building the project..."
    - npm run build
    - echo "Successfully built the project."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  only:          # Runs only during merge requests
    - merge_requests
  script:
    - echo "Running unit tests... This will take some time."
    - npm run test
    - echo "Successfully passed unit tests."
