version: '3.7'
services:
  backend:
    container_name: ${WALLET_SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
#      args:
#        GL_NPM_TOKEN:
    volumes:
      - .:/usr/src/app
      - wallet-nodemodules:/usr/src/app/node_modules
    ports:
      - ${WALLET_APP_PORT}:${WALLET_APP_PORT}
      # - 50053:5000 # GRPC external port (for bloomRPC debugging)
      - 9223:9229 # Debug external port (for vscode debugging)
    command: npm run start:debug
    env_file:
      - .env.dev
    networks:
      - ${WALLET_SERVICE_NETWORK_NAME}
      - ${GRPC_NETWORK_NAME}
    # depends_on:
    #   - db
  db:
    container_name: ${WALLET_DB_CONTAINER_NAME}
    platform: linux/x86_64
    image: mysql:5.7@sha256:9415bfb9a83752d30b6395c84dde03573eeba7b5b9c937c0e09c3e7b32c76c93
    restart: always
    networks:
      - ${WALLET_SERVICE_NETWORK_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${WALLET_DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${WALLET_DB_PORT}:${DB_PORT}
    volumes:
      - wallet-mysql-db:/var/lib/mysql
networks:
  wallet-network:
  grpc-network:
volumes:
  wallet-mysql-db:
  wallet-nodemodules:
